language: php

php:
  - 7.1

sudo: false

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_script:
  - composer self-update
  - COMPOSER_DISCARD_CHANGES=1 composer install --dev --prefer-source --no-interaction
script:
  - composer test
