language: php

php:
  - 7.1
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - COMPOSER_DISCARD_CHANGES=1 composer update --prefer-source --no-interaction
script:
  - composer test
